import {Entity, model, property} from '@loopback/repository';

@model({
  settings: {
    idInjection: false,
    postgresql: {schema: 'cmdb', table: 'instance_operation'}
  }
})
export class InstanceOperation extends Entity {
  @property({
    type: 'string',
    required: false,
    jsonSchema: {nullable: false},
    description: "autogenerated record GUID",
    id: 1,
    postgresql: {columnName: 'instance_operation_uid', dataType: 'uuid', dataLength: null, dataPrecision: null, dataScale: null, nullable: 'NO', generated: true},
  })
  instanceOperationUid: string;

  @property({
    type: 'string',
    jsonSchema: {nullable: false},
    length: 63,
    description: 'string from lookup table operation',
    postgresql: {columnName: 'operation', dataType: 'character varying', dataLength: 63, dataPrecision: null, dataScale: null, nullable: 'NO', generated: undefined},
  })
  operation: string;

  @property({
    type: 'string',
    required: false,
    jsonSchema: {nullable: false},    
    postgresql: {columnName: 'instance_uid', dataType: 'uuid', dataLength: null, dataPrecision: null, dataScale: null, nullable: 'NO', generated: undefined},
  })
  instanceUid: string;

  @property({
    type: 'date',
    jsonSchema: {nullable: false},    
    postgresql: {columnName: 'dt_start', dataType: 'timestamp with time zone', dataLength: null, dataPrecision: null, dataScale: null, nullable: 'NO', generated: true},
  })
  dtStart: string;

  @property({
    type: 'date',
    jsonSchema: {nullable: true},
    description: "NOT NULL when completed",
    postgresql: {columnName: 'dt_finish', dataType: 'timestamp with time zone', dataLength: null, dataPrecision: null, dataScale: null, nullable: 'YES', generated: undefined},
  })
  dtFinish?: string;

  @property({
    type: 'boolean',
    jsonSchema: {nullable: true},
    description: "to be set on completion",
    postgresql: {columnName: 'is_successful', dataType: 'boolean', dataLength: null, dataPrecision: null, dataScale: null, nullable: 'YES', generated: undefined},
  })
  isSuccessful: boolean;
/*
  @property({
    type: 'string',
    jsonSchema: {nullable: true},
    length: 31,    
    postgresql: {columnName: 'stage', dataType: 'character varying', dataLength: 31, dataPrecision: null, dataScale: null, nullable: 'YES', generated: undefined},
  })
  stage?: string;

  @property({
    type: 'string',
    jsonSchema: {nullable: true},    
    postgresql: {columnName: 'instance_operation_stage_uid', dataType: 'uuid', dataLength: null, dataPrecision: null, dataScale: null, nullable: 'YES', generated: undefined},
  })
  instanceOperationStageUid?: string;
*/
  // Define well-known properties here

  // Indexer property to allow additional data
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  [prop: string]: any;

  constructor(data?: Partial<InstanceOperation>) {
    super(data);
  }
}

export interface InstanceOperationRelations {
  // describe navigational properties here
}

export type InstanceOperationWithRelations = InstanceOperation & InstanceOperationRelations;
