import {Entity, model, property} from '@loopback/repository';

@model({
  settings: {
    idInjection: false,
    postgresql: {schema: 'cmdb', table: 'service_instance_v03'}
  }
})
export class ServiceInstanceV03 extends Entity {
  @property({
    type: 'string',
    required: false,
    jsonSchema: {nullable: false},    
    id: 1,
	description: "autogenerated record GUID",
    postgresql: {columnName: 'service_instance_version_uid', dataType: 'uuid', dataLength: null, dataPrecision: null, dataScale: null, nullable: 'NO', generated: true},
  })
  serviceInstanceVersionUid: string;

  @property({
    type: 'number',
    required: true,
    jsonSchema: {nullable: false},
    scale: 0, 
	description: "instance version serial number, 1-based, unique for each service_instance_uid",	
    postgresql: {columnName: 'version', dataType: 'integer', dataLength: null, dataPrecision: null, dataScale: 0, nullable: 'NO', generated: undefined},
  })
  version: number;

  @property({
    type: 'string',
    required: true,
    jsonSchema: {nullable: false},    
	description: "service instance guid",	
    postgresql: {columnName: 'service_instance_uid', dataType: 'uuid', dataLength: null, dataPrecision: null, dataScale: null, nullable: 'NO', generated: undefined},
  })
  serviceInstanceUid: string;

  @property({
    type: 'string',
    jsonSchema: {nullable: true},
    length: 255,    
    postgresql: {columnName: 'display_name', dataType: 'character varying', dataLength: 255, dataPrecision: null, dataScale: null, nullable: 'YES', generated: undefined},
  })
  displayName?: string;

  @property({
    type: 'number',
    required: true,
    jsonSchema: {nullable: false},
    scale: 0,    
	description: "service id from service catalog. TODO: add service version",	
    postgresql: {columnName: 'service_id', dataType: 'integer', dataLength: null, dataPrecision: null, dataScale: 0, nullable: 'NO', generated: undefined},
  })
  serviceId: number;

  @property({
    type: 'number',
    jsonSchema: {nullable: true},
    scale: 0,    
    postgresql: {columnName: 'specification_item_id', dataType: 'integer', dataLength: null, dataPrecision: null, dataScale: 0, nullable: 'YES', generated: undefined},
  })
  specificationItemId?: number;

  @property({
    type: 'number',
    jsonSchema: {nullable: true},
    scale: 0,    
    postgresql: {columnName: 'creator_id', dataType: 'integer', dataLength: null, dataPrecision: null, dataScale: 0, nullable: 'YES', generated: undefined},
  })
  creatorId?: number;

  @property({
    type: 'number',
    jsonSchema: {nullable: true},
    scale: 0,    
    postgresql: {columnName: 'updater_id', dataType: 'integer', dataLength: null, dataPrecision: null, dataScale: 0, nullable: 'YES', generated: undefined},
  })
  updaterId?: number;

  @property({
    type: 'date',
    required: false,
    jsonSchema: {nullable: false},    
    postgresql: {columnName: 'dt_created', dataType: 'timestamp without time zone', dataLength: null, dataPrecision: null, dataScale: null, nullable: 'NO', generated: true},
  })
  dtCreated: string;

  @property({
    type: 'date',
    required: false,
    jsonSchema: {nullable: false},    
    postgresql: {columnName: 'dt_updated', dataType: 'timestamp without time zone', dataLength: null, dataPrecision: null, dataScale: null, nullable: 'NO', generated: true},
  })
  dtUpdated: string;

  @property({
    type: 'boolean',
    required: true,
    jsonSchema: {nullable: false},    
    postgresql: {columnName: 'is_deleted', dataType: 'boolean', dataLength: null, dataPrecision: null, dataScale: null, nullable: 'NO', generated: undefined},
  })
  isDeleted: boolean;

  @property({
    type: 'boolean',
    required: true,
    jsonSchema: {nullable: false},    
    postgresql: {columnName: 'is_test', dataType: 'boolean', dataLength: null, dataPrecision: null, dataScale: null, nullable: 'NO', generated: undefined},
  })
  isTest: boolean;

  @property({
    type: 'object',
    required: true,
    jsonSchema: {nullable: false},    
    postgresql: {columnName: 'status', dataType: 'jsonb', dataLength: null, dataPrecision: null, dataScale: null, nullable: 'NO', generated: undefined},
  })
  status: object;

  @property({
    type: 'object',
    jsonSchema: {nullable: true},    
    postgresql: {columnName: 'instance_data', dataType: 'jsonb', dataLength: null, dataPrecision: null, dataScale: null, nullable: 'YES', generated: undefined},
  })
  instanceData?: object;

  @property({
    type: 'string',
    jsonSchema: {nullable: true},    
    postgresql: {columnName: 'descr', dataType: 'text', dataLength: null, dataPrecision: null, dataScale: null, nullable: 'YES', generated: undefined},
  })
  descr?: string;

  // Define well-known properties here

  // Indexer property to allow additional data
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  [prop: string]: any;

  constructor(data?: Partial<ServiceInstanceV03>) {
    super(data);
  }
}

export interface ServiceInstanceV03Relations {
  // describe navigational properties here
}

export type ServiceInstanceV03WithRelations = ServiceInstanceV03 & ServiceInstanceV03Relations;
